-- MySQL Script generated by MySQL Workbench
-- Thứ hai, 25 Tháng sáu Năm 2018 15:12:47 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema NodeJS_MySQL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NodeJS_MySQL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NodeJS_MySQL` DEFAULT CHARACTER SET utf8 ;
USE `NodeJS_MySQL` ;

-- -----------------------------------------------------
-- Table `NodeJS_MySQL`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NodeJS_MySQL`.`User` (
  `IdUser` INT(11) NOT NULL,
  `nameUser` VARCHAR(45) NOT NULL,
  `emailUser` VARCHAR(45) NOT NULL,
  `addressUser` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `NodeJS_MySQL`.`devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NodeJS_MySQL`.`devices` (
  `idDevice` INT(11) NOT NULL,
  `nameDevice` VARCHAR(45) NOT NULL,
  `idUser` INT(11) NOT NULL,
  PRIMARY KEY (`idDevice`, `idUser`),
  INDEX `idUser_idx` (`idUser` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `NodeJS_MySQL`.`User` (`IdUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
